jobs:

- name: setStorageBase
  job:
    set:
      val: "Nothing here"

- name: deployStorageK
  job:
    deploy:
      contract: apir.sol
      wait: true

- name: setStorage
  job:
    call:
      destination: $deployStorageK
      data: set $setStorageBase
      wait: true

- name: queryStorage
  job:
    query-contract:
      destination: $deployStorageK
      data: get

- name: assertStorage
  job:
    assert:
      key: $queryStorage
      relation: eq
      val: $setStorageBase
